name: Technique Feedback
description: Send us technique(s) you would like to address
title: "[Technique Feedback]: "
labels: ["Technique Feedback"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this form!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: existTechnique
    attributes:
      label: Existing Technique Link
      description: If this is an existing technique. Please include the link to the existing technique.
      placeholder: ex. https://atlas.mitre.org/techniques/AML.T0000
    validations:
      required: false
  - type: input
    id: newTechnique
    attributes:
      label: New Technique
      description: |
        If proposing a new technique, name it here.
    validations:
      required: false
  - type: textarea
    id: techniquePropsal
    attributes:
      label: Technique Suggestion
      description: |
        Please describe why this technique needs changing. 
        Does the technique need additional information?
        
      value: |
        If this is a new technique, what tactic(s) does it fall under?

        If it's a subtechnique, what is its parent?
        
        ## Proposal 

        ## Other links/references

    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers were you on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
